import { useState } from 'react';
import { motion } from 'framer-motion';
import { CheckCircle2, Circle, Download, ArrowRight, FileText, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useNavigate } from 'react-router-dom';

export function SetupChecklistPage() {
  const navigate = useNavigate();
  const [completedItems, setCompletedItems] = useState<Set<string>>(new Set());

  const checklistItems = [
    {
      id: 'business-registration',
      title: 'Register Your Business',
      description: 'Register as a sole trader or limited company with HMRC',
      category: 'Legal & Compliance',
    },
    {
      id: 'insurance',
      title: 'Get Public Liability Insurance',
      description: 'Essential insurance to protect your business (typically £5-15/month)',
      category: 'Legal & Compliance',
    },
    {
      id: 'equipment',
      title: 'Purchase Essential Equipment',
      description: 'Squeegees, buckets, cleaning solutions, ladders, extension poles',
      category: 'Equipment',
    },
    {
      id: 'vehicle',
      title: 'Set Up Your Vehicle',
      description: 'Organize equipment storage, water tanks if needed, signage',
      category: 'Equipment',
    },
    {
      id: 'pricing',
      title: 'Set Your Pricing Structure',
      description: 'Determine standard prices for different property types',
      category: 'Business Setup',
    },
    {
      id: 'bank-account',
      title: 'Open Business Bank Account',
      description: 'Separate business finances from personal (optional but recommended)',
      category: 'Business Setup',
    },
    {
      id: 'marketing',
      title: 'Plan Your Marketing',
      description: 'Business cards, flyers, social media, local advertising',
      category: 'Marketing',
    },
    {
      id: 'software',
      title: 'Set Up Business Management Software',
      description: 'Use SoloWipe to manage customers, jobs, and payments',
      category: 'Business Setup',
    },
    {
      id: 'first-customers',
      title: 'Get Your First Customers',
      description: 'Start with friends, family, local businesses, door-to-door canvassing',
      category: 'Marketing',
    },
    {
      id: 'direct-debit',
      title: 'Set Up Direct Debit Collection',
      description: 'Use GoCardless to automatically collect payments (via SoloWipe)',
      category: 'Business Setup',
    },
  ];

  const toggleItem = (id: string) => {
    setCompletedItems((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const completionPercentage = (completedItems.size / checklistItems.length) * 100;

  const handleDownload = () => {
    // Create a simple text version for download
    const text = `Window Cleaning Business Setup Checklist\n\n` +
      checklistItems.map((item, index) => 
        `${index + 1}. [${completedItems.has(item.id) ? '✓' : ' '}] ${item.title}\n   ${item.description}\n`
      ).join('\n') +
      `\n\nGenerated by SoloWipe - https://solowipe.co.uk`;
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'window-cleaning-setup-checklist.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const categories = Array.from(new Set(checklistItems.map(item => item.category)));

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary/5 via-background to-emerald-500/5 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-8"
        >
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-primary/10 mb-4">
            <FileText className="w-8 h-8 text-primary" />
          </div>
          <h1 className="text-4xl font-bold text-foreground mb-3">
            Window Cleaning Business Setup Checklist
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-6">
            A comprehensive checklist to help you start your window cleaning business the right way
          </p>
          
          {/* Progress */}
          <div className="max-w-md mx-auto">
            <div className="flex items-center justify-between text-sm mb-2">
              <span className="text-muted-foreground">Progress</span>
              <span className="font-semibold text-foreground">
                {completedItems.size} of {checklistItems.length} completed
              </span>
            </div>
            <div className="w-full bg-muted rounded-full h-3 overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${completionPercentage}%` }}
                transition={{ duration: 0.5 }}
                className="h-full bg-primary rounded-full"
              />
            </div>
          </div>
        </motion.div>

        {/* Actions */}
        <div className="flex items-center justify-center gap-4 mb-8">
          <Button
            variant="outline"
            onClick={handleDownload}
            className="gap-2"
          >
            <Download className="w-4 h-4" />
            Download Checklist
          </Button>
          <Button
            onClick={() => navigate('/auth?mode=signup')}
            className="gap-2"
          >
            Get Started with SoloWipe
            <ArrowRight className="w-4 h-4" />
          </Button>
        </div>

        {/* Checklist by Category */}
        <div className="space-y-6">
          {categories.map((category) => {
            const categoryItems = checklistItems.filter(item => item.category === category);
            return (
              <Card key={category}>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-primary" />
                    {category}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {categoryItems.map((item) => {
                      const isCompleted = completedItems.has(item.id);
                      return (
                        <motion.div
                          key={item.id}
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          className={`
                            flex items-start gap-3 p-4 rounded-xl border transition-all cursor-pointer
                            ${isCompleted 
                              ? 'bg-primary/5 border-primary/20' 
                              : 'bg-muted/50 border-border hover:border-primary/30'
                            }
                          `}
                          onClick={() => toggleItem(item.id)}
                        >
                          <button
                            className="mt-0.5 flex-shrink-0"
                            aria-label={isCompleted ? 'Mark as incomplete' : 'Mark as complete'}
                          >
                            {isCompleted ? (
                              <CheckCircle2 className="w-6 h-6 text-primary" />
                            ) : (
                              <Circle className="w-6 h-6 text-muted-foreground" />
                            )}
                          </button>
                          
                          <div className="flex-1 min-w-0">
                            <h3 className={`
                              font-semibold text-foreground mb-1
                              ${isCompleted && 'line-through text-muted-foreground'}
                            `}>
                              {item.title}
                            </h3>
                            <p className="text-sm text-muted-foreground">
                              {item.description}
                            </p>
                          </div>
                        </motion.div>
                      );
                    })}
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* CTA Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mt-12"
        >
          <Card className="bg-gradient-to-br from-primary/10 to-emerald-500/10 border-primary/20">
            <CardHeader>
              <CardTitle>Ready to Start Your Business?</CardTitle>
              <CardDescription>
                SoloWipe helps you manage customers, schedule jobs, and collect payments automatically
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Button
                onClick={() => navigate('/auth?mode=signup')}
                size="lg"
                className="w-full"
              >
                Start Free - 10 Jobs Included
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}





