// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables with detailed error messages
// Don't throw errors immediately - log them and create a placeholder client
// This allows the app to render and show error messages instead of white screen

let supabase: ReturnType<typeof createClient<Database>>;
let supabaseError: Error | null = null;

function logSupabaseError(message: string, details?: string) {
  const fullMessage = details ? `${message}\n\n${details}` : message;
  console.error('[Supabase Configuration Error]', fullMessage);
  supabaseError = new Error(message);
}

if (!SUPABASE_URL) {
  logSupabaseError(
    'Missing VITE_SUPABASE_URL environment variable.',
    `Please add this to Netlify:
1. Go to Site settings → Environment variables
2. Add: VITE_SUPABASE_URL = https://your-project.supabase.co

Current value: ${SUPABASE_URL || 'undefined'}`
  );
} else if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_URL.includes('.supabase.co')) {
  logSupabaseError(
    'Invalid VITE_SUPABASE_URL format.',
    `Expected: https://xxxxx.supabase.co
Current value: ${SUPABASE_URL}`
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  logSupabaseError(
    'Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable.',
    `Please add this to Netlify:
1. Go to Site settings → Environment variables
2. Add: VITE_SUPABASE_PUBLISHABLE_KEY = sb_publishable_...

Get this from Supabase Dashboard → Project Settings → API → Publishable Keys

Current value: ${SUPABASE_PUBLISHABLE_KEY ? '***' + SUPABASE_PUBLISHABLE_KEY.slice(-10) : 'undefined'}`
  );
} else if (!SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_') && !SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
  logSupabaseError(
    'Invalid VITE_SUPABASE_PUBLISHABLE_KEY format.',
    `Should start with sb_publishable_ or eyJ
Current value: ${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...`
  );
}

// Only create client if we have valid credentials
if (!supabaseError && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  try {
    supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
    
    console.log('[Supabase] Client initialized successfully');
  } catch (error) {
    logSupabaseError(
      'Failed to initialize Supabase client',
      error instanceof Error ? error.message : 'Unknown error'
    );
    // Create a mock client to prevent app crash
    supabase = createClient<Database>('https://placeholder.supabase.co', 'placeholder-key');
  }
} else {
  // Create a placeholder client to prevent app crash
  // The app will show error messages via ErrorBoundary
  supabase = createClient<Database>('https://placeholder.supabase.co', 'placeholder-key');
  console.warn('[Supabase] Using placeholder client due to configuration errors');
}

// Export error for ErrorBoundary to display
export const getSupabaseError = () => supabaseError;

export { supabase };